In [1]:
import glob
import pandas as pd

In [2]:
files = glob.glob("snapshot_to_shortdesc//data/results_*.jsonl")
files

['snapshot_to_shortdesc//data/results_refugee_batch1.jsonl',
 'snapshot_to_shortdesc//data/results_prwp_batch1.jsonl',
 'snapshot_to_shortdesc//data/results_prwp_batch2.jsonl']

In [3]:
df = pd.concat([pd.read_json(x, lines=True) for x in files])
df

,snapshot_id,image_path,source_label,llm_output,raw_output,usage,cost,error
0,112_IDAR2016-0221-PAD-09012016_table_007.png,data/refugee_batch1/112_IDAR2016-0221-PAD-0901...,Refugee,{'visible_text_label': 'Consultancy Assignment...,"```json\n{\n ""visible_text_label"": ""Consultan...","{'input_tokens': 26304, 'input_tokens_details'...","{'input_tokens': 26304, 'output_tokens': 121, ...",NaN
1,056_Niger-COVID-19-Emergency-Response-Project_...,data/refugee_batch1/056_Niger-COVID-19-Emergen...,Refugee,"{'visible_text_label': 'Figure 1: Countries, t...","{\n ""visible_text_label"": ""Figure 1: Countrie...","{'input_tokens': 37607, 'input_tokens_details'...","{'input_tokens': 37607, 'output_tokens': 142, ...",NaN
2,194_multi-page_figure_000.png,data/refugee_batch1/194_multi-page_figure_000.png,Refugee,{'visible_text_label': 'Annex 10: Country at a...,"```json\n{\n ""visible_text_label"": ""Annex 10:...","{'input_tokens': 37681, 'input_tokens_details'...","{'input_tokens': 37681, 'output_tokens': 162, ...",NaN
3,069_Pakistan-Strengthening-Institutions-for-Re...,data/refugee_batch1/069_Pakistan-Strengthening...,Refugee,{'visible_text_label': 'Project Development Ob...,"{\n ""visible_text_label"": ""Project Developmen...","{'input_tokens': 49016, 'input_tokens_details'...","{'input_tokens': 49016, 'output_tokens': 118, ...",NaN
4,202_multi0page_table_007.png,data/refugee_batch1/202_multi0page_table_007.png,Refugee,{'visible_text_label': 'Annex 6 El Nino Emerge...,"```json\n{\n ""visible_text_label"": ""Annex 6\n...","{'input_tokens': 37654, 'input_tokens_details'...","{'input_tokens': 37654, 'output_tokens': 141, ...",NaN
...,...,...,...,...,...,...,...,...
527,document_717473_table_013.png,../../../data/snapshots/prwp_batch2/document_7...,PRWP,{'visible_text_label': 'Table 14 Demand for wa...,"```json\n{\n ""visible_text_label"": ""Table 14\...","{'input_tokens': 26530, 'input_tokens_details'...","{'input_tokens': 26530, 'output_tokens': 147, ...",NaN
528,document_15348558_figure_005.png,../../../data/snapshots/prwp_batch2/document_1...,PRWP,{'visible_text_label': 'Figure 5c. Financial D...,"```json\n{\n ""visible_text_label"": ""Figure 5c...","{'input_tokens': 48949, 'input_tokens_details'...","{'input_tokens': 48949, 'output_tokens': 152, ...",NaN
529,document_12714605_table_000.png,../../../data/snapshots/prwp_batch2/document_1...,PRWP,{'visible_text_label': 'Land Sales by MMRDA at...,"```json\n{\n ""visible_text_label"": ""Land Sale...","{'input_tokens': 37620, 'input_tokens_details'...","{'input_tokens': 37620, 'output_tokens': 136, ...",NaN
530,document_698797_table_000.png,../../../data/snapshots/prwp_batch2/document_6...,PRWP,{'visible_text_label': 'Table 1: Determinants ...,"```json\n{\n ""visible_text_label"": ""Table 1: ...","{'input_tokens': 26485, 'input_tokens_details'...","{'input_tokens': 26485, 'output_tokens': 152, ...",NaN
531,document_7471923_table_003.png,../../../data/snapshots/prwp_batch2/document_7...,PRWP,{'visible_text_label': 'GMM Estimation of Net ...,"{\n ""visible_text_label"": ""GMM Estimation of ...","{'input_tokens': 37589, 'input_tokens_details'...","{'input_tokens': 37589, 'output_tokens': 148, ...",NaN

In [4]:
df = df.join(pd.json_normalize(df["cost"]))

In [5]:
df["total_cost_usd"].sum()

np.float64(8.059959)

In [6]:
df["total_cost_usd"].mean()

np.float64(0.005644228991596638)

In [7]:
df["total_cost_usd"].std()

np.float64(0.0014085130261105216)

In [8]:
df.groupby("source_label").agg(
    count=("source_label", "count"),
    total_cost_usd=("total_cost_usd", "sum"),
)

              count  total_cost_usd
source_label
PRWP            929        5.247160
Refugee         499        2.812799